### ISSUE TITLE
add google analytics

### ISSUE THREAD

**Issue by tomahawk-pilot** [coronasafe/india-maps#12]
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-160173841-19"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-160173841-19');
</script>

**Comment by gigincg** [comment]
Changed? Already had a GA tag. should I remove that??
