### ISSUE TITLE
Fix the international data api

### ISSUE THREAD

**Issue by bodhish** [coronasafe/india-maps#15]
It's looks like the API is for return any reososne.
Its currently disabled by #14

**Comment by santhosh-ps** [comment]
#18 should fix this.

**Comment by gigincg** [comment]
The International API is broken again. Commented it out for a temporary fix

**Comment by santhosh-ps** [comment]
I am looking into this one.

**Comment by santhosh-ps** [comment]
Please check the PR and let me know if we need to do anything els. @gigincg
