### ISSUE TITLE
The District wise data shown is inaccurate

### ISSUE THREAD

**Issue by R-Aravind** [coronasafe/india-maps#17]
### **District wise data is wrong**
![image](https://user-images.githubusercontent.com/44097855/77562773-79031500-6ee6-11ea-9406-36b78d3aaafa.png)

### **The response from the API is inaccurate.**
![image](https://user-images.githubusercontent.com/44097855/77563151-e7e06e00-6ee6-11ea-9855-b20d38d4606c.png)

**Comment by bodhish** [comment]
FIxed
