### ISSUE TITLE
UI/UX Better visualization for Cases,Death,Recovered,Suspected

### ISSUE THREAD

**Issue by pshanoop** [coronasafe/india-maps#9]
I think it would much better if we have a better visualization, 

Confirmed cases, Recovered,Death, Suspected. 
For reference Please see the screenshot, This from a German daily, 
https://interaktiv.morgenpost.de/corona-virus-karte-infektionen-deutschland-weltweit/

![image](https://user-images.githubusercontent.com/1174257/77250076-ba28ca00-6c45-11ea-8cba-3374702580c2.png)

**Comment by gigincg** [comment]
I see you've forked the repo. If you're working on implementing this, we'd be happy to merge a PR

**Comment by pshanoop** [comment]
I'm not working with this. I have no clue in react
Let me check with some of my friend if he can help. 

I'm forked it for adding Docker.
